---
- name: Install apache packages 
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ successful_installs }}"
    
- name: ensure httpd is running
  service:
    name: httpd 
    state: started
  register: start_apache
  
- name: output register
  debug:
    var: start_apache
    
- name: createa file
  shell: touch /home/potu6
  when: 
    - start_apache is defined and not start_apache['failed']|bool
  register: debug
- name: debug
  debug:
    var: debug
    
- name: check var array
  ansible.builtin.copy:
    src: "{{ path[0] }}"
    dest: "{{ path[1] }}"
