---
- name: testing setfact
  ansible.builtin.set_fact:
    successful_installs: []
  register: success
  
- name: pirnt
  debug:
    var: success
  
  
- name: check directory exists
  shell: "ps -A | grep httpd | cat"
  register: dir_ex
