---
- name: default set
  set_fact:
    prior_install: "unknown"
    proceed: 0
    


#- name: perform all tasks
#  include_tasks: apache.yml
#  when:
   # - ansible_facts.distribution in ['Ubuntu']
 #   - install == 'yes'
#- name: perform all tasks
#  include_tasks: debug.yml
 # when:
  #  - ansible_facts.distribution in ['Ubuntu']
 #   - install == 'yes'

- name: get service facts
  ansible.builtin.service_facts:

- name: setfact1
  ansible.builtin.set_fact:
    ip_1: "{{ ansible_host }}"
  when: server_id != "2000"

- name: setfact2
  ansible.builtin.set_fact:
    ip_2: "{{ ansible_host }}"
  when: server_id == "2000" 
  
- name: touch file1
  shell: touch ~/potu2
  delegate_to: "{{ ip_1 }}"
  when: ip1 is defined
 
- name: touch file3
  shell: touch /home/filepotuu1
  delegate_to: "{{ ip_2 }}"
  when: ip2 is defined
  
- name: try to work out how to access the service
  debug:
    var: ansible_facts.services["NetworkManager-wait-online.service"]
  register: statusde
  
- name: edit sudo
  ansible.builtin.blockinfile:
    path: /etc/sudoers
    insertafter: 'root     ALL=(ALL)      ALL'
    block: |
      # give root
      %DBaas_Admins        ALL=(ALL)      ALL

- name: template sssd
  ansible.builtin.template:
    src: "tempsssd.j2"
    dest: /etc/selinux/targeted/active/modules/100/sssddbsssd.conf
    mode: '600'

- name: status
  shell: systemctl stop httpd
  when:
    - hostvars[inventory_hostname]['services']["NetworkManager-wait-online.service"]['state'] == "stopped"


- name: create dir
  shell: mkdir "{{ dest[0] }}/newdir4"
  register: dir
#- name: setfact check
 # set_fact:
  #  proceed: 1
  #when: 
  #- prior_install == 'done'
- name: debug
  debug:
    var: dir
 #   var: role_path
 
- name: chdir
  command: chdir=/home/saikiran
    mkdir chdir

  #when: 
  #- proceed == 1
- name: perform log task
  include_tasks: log.yml
  when:
  #  - ansible_facts.distribution in ['Ubuntu']
    - install == 'yes'
