---
- name: default set
  set_fact:
    prior_install: "unknown"
    proceed: 0

- name: perform all tasks
  include_tasks: apache.yml
  when:
    - install == 'yes'
- name: perform all tasks
  include_tasks: debug.yml
  when:
    - install == 'yes'


- name: setfact check
  set_fact:
    proceed: 1
  when: 
  - prior_install == 'done'
- name: debug
  debug:
    var: prior_install
- name: create dir
  shell: mkdir /home/newdir
  when: 
  - proceed == 1
