---
- name: default set
  set_fact:
    prior_install: "unknown"
    proceed: 0

#- name: perform all tasks
#  include_tasks: apache.yml
#  when:
   # - ansible_facts.distribution in ['Ubuntu']
 #   - install == 'yes'
#- name: perform all tasks
#  include_tasks: debug.yml
 # when:
  #  - ansible_facts.distribution in ['Ubuntu']
 #   - install == 'yes'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: {{ ansible_facts.services | state }}


- name: create dir
  shell: mkdir "{{ dest[0] }}/newdir4"
  register: dir
#- name: setfact check
 # set_fact:
  #  proceed: 1
  #when: 
  #- prior_install == 'done'
- name: debug
  debug:
    var: dir
 #   var: role_path
 
- name: chdir
  command: chdir=/home/saikiran
    mkdir chdir

  #when: 
  #- proceed == 1
- name: perform log task
  include_tasks: log.yml
  when:
  #  - ansible_facts.distribution in ['Ubuntu']
    - install == 'yes'
