---
- name: default set
  set_fact:
    prior_install: "unknown"
    proceed: 0

#- name: perform all tasks
#  include_tasks: apache.yml
#  when:
   # - ansible_facts.distribution in ['Ubuntu']
 #   - install == 'yes'
- name: perform all tasks
  include_tasks: debug.yml
  when:
  #  - ansible_facts.distribution in ['Ubuntu']
    - install == 'yes'


- name: setfact check
  set_fact:
    proceed: 1
  when: 
  - prior_install == 'done'
- name: debug
  debug:
    var: prior_install
    var: role_path
- name: create dir
  shell: mkdir "{{ dest }}/newdir2"
  #when: 
  #- proceed == 1
- name: perform log task
  include_tasks: log.yml
  when:
  #  - ansible_facts.distribution in ['Ubuntu']
    - install == 'yes'
