---

- name: perform all tasks
  include: "test.yml"
    
- name: default set
  set_facts:
    prior_install: "unknown"
- name: debug
  debug:
    var: prior_install
    
- name: create dir
  shell: mkdir /home/newdir
  when: 
  - prior_install == 'done'
