---

- name: local directory in ect system
  ansible.builtin.file:
    path: "{{ path }}"
    group: root
    owner: root
  become: true
  become_user: root
- name: display message
  ansible.builtin.debug:
   msg:
   - "permissions changed '{{root}}' goood"

- name: check if user created
  stat:
    path: "{{ passpath }}"
  register: pass_file
 

- name: create a file
  shell: touch /home/tomcat
  when: pass_file.stat.exists



- name: check if service installed
  stat: 
    path: "{{ apache }}"
  register: service_file


- name: create a file
  shell: touch /home/tom
  when: service_file.stat.exists
  notify:
   - Restart apache
- name: copy file
  ansible.builtin.copy:
    src: "{{ source }}"
    dest: "{{ dest }}"
