---

- name: local directory in ect system
  ansible.builtin.file:
    path: "{{ path }}"
    group: root
    owner: root
  become: true
  become_user: root
- name: display message
  ansible.builtin.debug:
   msg:
   - "permissions changed '{{root}}' goood"

- name: check directory exists
  shell: "ps -A | grep httpd | cat"
  register: dir_ex
  
- name: set defaults
  set_fact: 
    dir_e: 0

- name: is apache running
  set_fact: 
    dir_e: 1
  when: dir_ex.stdout_lines | length >0
  
- name: create file
  shell: touch /home/potu2
  when:
  - dir_e == 1
 
- name: check if user created
  stat:
    path: "{{ passpath }}"
  register: pass_file
 

- name: create a file
  shell: touch /home/tomcat
  when: pass_file.stat.exists



- name: check if service installed
  stat: 
    path: "{{ apache }}"
  register: service_file


- name: create a file
  shell: touch /home/tom
  when: service_file.stat.exists
  notify:
   - Restart apache
- name: copy file
  ansible.builtin.copy:
    src: "{{ source }}"
    dest: "{{ dest }}"
